---
version: '3.4'

services:
  app:
    container_name: laravel
    image: zoom-auto-host-key/laravel:latest
    build:
      dockerfile: docker/Dockerfile
      args:
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2}
        NODE_VERSION: ${NODE_VERSION:-18-bookworm}
        PHP_VERSION: ${PHP_VERSION:-8.2-fpm-bookworm}
    ports:
      - ${APP_PORT:-80}:80
    environment:
      APP_SERVICE: ${APP_SERVICE:-laravel}
    volumes:
      - ${PWD}/.data/database:/var/www/html/database/sqlite
      - ${PWD}/.data/caddy/config:/root/.config/caddy
      - ${PWD}/.data/caddy/data:/root/.local/share/caddy
      - ${PWD}/.data/logs:/var/log
    networks:
      - lan
    restart: unless-stopped
    entrypoint:
      - /usr/local/bin/entrypoint

networks:
  lan:
    driver: bridge
    external: false
